#!/usr/bin/env sh

this="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

nosetests \
  --verbosity=1 \
  --ignore-files '^\.'\
  --ignore-files '^setup\.py$' \
  --with-doctest \
  --with-coverage \
  --cover-package=snv_spectrum \
  --where "${this}"/..
